USE biobank;
Drop Table FileMetaDataViewedBy;
Drop Table FileMetadata;
Drop Table CRCParticipant;
Drop Table PortalNotification;
Drop table EmailLog;
Drop table QuestionAnswer;
Drop table ProviderParticipant;
Drop Table User;
drop table Role;
drop table Code;
drop table CodeCategory;
